sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kaieulers/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kaieulers/docker-react npm run test
